// import Home from "../components/Home";
import Head from "next/head";

import Wrapper from "../components/Wrapper";

import VoteGrid from "../components/VoteGrid";

import { getRandomSetOfN } from "../getFakeData/getFakeData";

export default function Homepage({ cards }) {
  console.log(cards, 9);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        <div className="flex items-center col-start-2 col-end-9 mt-48">
          <div className="space-y-12 p-8 md:p-12 md:pr-24">
            <VoteGrid companies={cards} />
          </div>
        </div>
      </Wrapper>
    </>
  );
}

export async function getStaticProps() {
  let fakeProps = getRandomSetOfN(6);
  return {
    props: { cards: fakeProps },
  };
}
